upstream todotasks_frontend {
  server frontend:80;
}

upstream todotasks_backend {
  server backend:3000;
}

server {
  listen 80;
  server_name _;
  client_max_body_size 12m;

  location = /todotaskdev {
    return 301 /todotaskdev/;
  }

  location /todotaskdev/api/ {
    proxy_pass http://todotasks_backend/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /todotaskdev;
  }

  location /todotaskdev/docs {
    proxy_pass http://todotasks_backend/docs;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Prefix /todotaskdev;
  }

  location /todotaskdev/ {
    proxy_pass http://todotasks_frontend/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    try_files $uri $uri/ /index.html;
  }
}
